.0pdd.yml, .rultor.yml, .travis.yml, README.md
PR for #2 
added all 3 of them
=> Travis, rultor and 0pdd

.rultor.yml, .travis.yml, checkstyle.xml, pom.xml, src/main/java/com/selfxdsd/selfweb/SelfWebApplication.java, src/test/java/com/selfxdsd/selfweb/SelfWebApplicationTests.java
=> #5 checkstyle installed

.rultor.yml, .travis.yml, pom.xml, src/test/java/com/selfxdsd/selfweb/SelfWebApplicationITCase.java
=> #8 maven-failsafe for Integration Tests

.travis.yml, pom.xml
=> #6 jacoco and coveralls

checkstyle.xml, pom.xml, src/main/java/com/selfxdsd/selfweb/IndexController.java, src/main/resources/templates/header.html, src/main/resources/templates/index.html
=> #11 index page and thymeleaf

pom.xml, src/main/java/com/selfxdsd/selfweb/SelfWebApplication.java, src/main/resources/application.properties, src/main/resources/templates/head.html, src/main/resources/templates/header.html, src/main/resources/templates/index.html
=> #13 Github login/logout implemented

src/main/java/com/selfxdsd/selfweb/SelfWebApplication.java, src/main/resources/templates/header.html
PR for #14 
First sketch styling of the navbar
=> First sketch of navbar

src/main/resources/templates/footer.html, src/main/resources/templates/head.html, src/main/resources/templates/index.html
fixes #20. Adds footer and command to work in the responsive way.
As always, feel free to refuse it.
Thanks.
=> Adds footer

src/main/java/com/selfxdsd/selfweb/ReposController.java, src/main/resources/public/js/getPublicRepos.js, src/main/resources/templates/header.html, src/main/resources/templates/repositories.html
=> Repos page scaffolding

src/main/java/com/selfxdsd/selfweb/SelfWebApplication.java, src/main/java/com/selfxdsd/selfweb/api/BaseApiController.java, src/main/java/com/selfxdsd/selfweb/api/Projects.java, src/main/java/com/selfxdsd/selfweb/api/Users.java, src/main/resources/application.properties, src/main/resources/templates/head.html
=> #27 Endpoint for JSON project

src/main/resources/public/js/getPublicRepos.js, src/main/resources/templates/head.html, src/main/resources/templates/repositories.html
=> #17 datatable and accordion scaffolding for repos

src/main/resources/public/css/main.css, src/main/resources/templates/repositories.html
PR for #17 
Repos are displayed in tabs
=> #17 repo tabs

pom.xml, src/main/java/com/selfxdsd/selfweb/api/Repositories.java, src/main/resources/application.properties
This endpoint returns all the Org repos to which the user has admin rights.
Left puzzle for continuing with the front-end.
=> #33 Endpoint to read Org Repos from Github

src/main/java/com/selfxdsd/selfweb/LoginProducer.java
- creates Login objects based on the authenticated client (Github, Gitlab etc..).
- implemented GithubLogin and GitlabLogin.
PR for #28
=> #28 LoginProducer refactoring.

pom.xml, src/main/java/com/selfxdsd/selfweb/LoginProducer.java, src/main/java/com/selfxdsd/selfweb/api/Users.java
Fixes #45 
Left puzzle to set the admin role for any User who is an admin on the "self-xdsd" organization.
=> #45 Login now registers the User's role

src/main/resources/public/css/main.css, src/main/resources/public/js/getOrgRepos.js, src/main/resources/public/js/getPublicRepos.js, src/main/resources/templates/footer.html, src/main/resources/templates/head.html, src/main/resources/templates/header.html, src/main/resources/templates/repositories.html
=> #48 getRepos bugfix + styling

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ProjectManagersApi.java, src/main/java/com/selfxdsd/selfweb/api/input/PmInput.java, src/main/resources/public/js/getPms.js, src/main/resources/templates/projectManagers.html
Fixes #54 
* Updated self-core to 0.0.16
* Updated self-storage to 0.0.6
* Displayed PM commission as well as modified the Add PM form to accept the commission + validation.
=> #54 updated core/storage + PM commission

src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonProject.java, src/main/resources/public/js/getProject.js, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/ProjectsApiTestCase.java
PR #58 
Project ownership logic updated to reflect multiple Organization admins.
Left puzzle to unify the project(...) endpoint to work for all providers
=> #58 Possibility of Multiple Org admins.

src/main/resources/public/js/getOrgRepos.js
=> #62 Ensure org repos are at least an empty array.

src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/resources/public/js/getProject.js, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/ProjectsApiTestCase.java
=> #61 Endpoint 'project' works for all providers.

src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/java/com/selfxdsd/selfweb/api/output/AbstractJsonArray.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContracts.java, src/test/java/com/selfxdsd/selfweb/api/ProjectsApiTestCase.java
- implemented and tested.
- added output abstractions for json Contract/Contracts.
- updated puzzle.
PR for #59
=> #59. ProjectsApi contracts endpoint.

src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/java/com/selfxdsd/selfweb/api/input/ContractInput.java, src/main/java/com/selfxdsd/selfweb/api/input/validators/Role.java, src/main/java/com/selfxdsd/selfweb/api/input/validators/RoleValidator.java, src/main/java/com/selfxdsd/selfweb/api/input/validators/ValidRole.java, src/test/java/com/selfxdsd/selfweb/api/ProjectsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/input/validators/RoleValidatorTestCase.java
- added Role validator for inputs.
- added ContractInput.
- implemented + tested form endpoint for adding a contract.
- updated puzzle.
PR for #67
=> #67. Implemented + tested adding project contract.

pom.xml
=> #70 core 20, storage 7

src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/resources/public/css/main.css, src/main/resources/public/js/contractsService.js, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/templates/project.html
- js interactor with ProjectsApi.
- for UI testing xhr  were intercepted locally with jquery-mockjax plugin.
PR for #69
=> #69. Project Contracts UI.

src/main/java/com/selfxdsd/selfweb/api/BaseApiController.java
=> #76. Custom message for 500 error code.

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/templates/project.html
=> #77. Contract form `hourlyRate` field is never empty onPost.

src/main/java/com/selfxdsd/selfweb/SelfWebApplication.java, src/main/resources/templates/head.html
Fixes #82 
Unauthorized /api calls return status UNAUTHORIZED.
Unauthorized page access redirects to homepage.
=> #82 handle unautorized better

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/templates/head.html
=> #80. Contracts front-end form validation.

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/ProjectsApiTestCase.java
=> #75. Moved ProjectsApi contracts methods to ContractsApi.

pom.xml
=> #87 updated versions

src/main/java/com/selfxdsd/selfweb/ContributorDashBoardController.java, src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContributor.java, src/main/resources/templates/contributor.html, src/main/resources/templates/header.html, src/test/java/com/selfxdsd/selfweb/api/ContributorsApiTestCase.java
Fixes #89 
HTML scaffolding
Implemented and tested ContributorApi.contributor()
Left puzzle to continue with the front-end.
=> #89 ContributorApi started implementation + tests

src/main/resources/public/css/main.css, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html, src/main/resources/templates/project.html, src/main/resources/templates/projectManagers.html
=> Contributorpage

src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoice.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoices.java, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html
PR for #91, WIP.
* Display Contract Tasks
* Added endpoint to get Contract Invoices
* Next step: display the invoices as well
* Write tests for the GET contract invoices endpoint
=> #91 more work on Contributor Dashboard page

src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/java/com/selfxdsd/selfweb/api/output/AbstractJsonObject.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoice.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoicedTask.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoicedTasks.java, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html
PR for #91 
Contributor can now download his contract Invoices as PDF.
=> #91 download PDF invoice

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/java/com/selfxdsd/selfweb/api/PayoutMethodsApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonPayoutMethod.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonPayoutMethods.java, src/main/resources/public/css/main.css, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html, src/main/resources/templates/head.html
PR for #91
Implemented Payout Methods tab, where the contributor can create their Stripe Connect Account.
=> #91 Payout Methods tab implemented

src/main/resources/public/css/main.css
=> #102 Removed dropdown arrow from avatar dropdown menu.

src/main/java/com/selfxdsd/selfweb/api/PayoutMethodsApi.java, src/main/resources/public/js/getAndAddContracts.js
- left puzzle for autocomplete for contributor username field in contracts project contracts tab.
PR for #100
=> #100. Self xdsd base url sysenv variable.

src/main/java/com/selfxdsd/selfweb/SelfCoreComponent.java, src/main/java/com/selfxdsd/selfweb/api/PayoutMethodsApi.java
Fixes #105 
Renamed:
db.user         -> self_db_user
db.password ->self_db_password
db.url            -> self_db_url
self.xdsd.base.url -> self_xdsd_base_url
=> #105 renamed env variables

src/main/resources/public/js/getProject.js, src/main/resources/templates/project.html
PR for #109 
It's on the Project Overview tab and it looks like this:
=> #109 badge card implemented

src/main/java/com/selfxdsd/selfweb/TestEnvFilter.java, src/main/resources/templates/header.html
Fixes #113 
It looks like this:
=> #113 test banner implemented

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/templates/project.html
=> #117 styling for project contracts tab

src/main/java/com/selfxdsd/selfweb/api/input/ContractInput.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/usersService.js, src/main/resources/templates/head.html, src/main/resources/templates/project.html
Fixes #119 
Also contains small bugfixes in the AddContractForm.
=> #119 Remove JQuery Validator

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/templates/project.html
Fixes #122 
Contracts tab of the Project page: show Tasks table on click
Added other icons in the Options column
=> #122 Show Contract Tasks

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/templates/project.html
Fixes #121 
Implementing the download of the active Invoice of a project Contract.
Also some fixes.
=> #121 download a contract's active Invoice

src/main/resources/application.properties, src/main/resources/templates/footer.html
The footer should be now on the bottom of every page. Let me know if everything is ok :D
=> Footer down on the page

src/main/resources/public/css/main.css, src/main/resources/templates/index.html
Fixes #132 The content should be displayed properly now.
=> Responsiveness bug solved

src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonWallet.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonWallets.java, src/main/resources/public/css/main.css, src/main/resources/public/js/getProject.js, src/main/resources/templates/project.html
fixes #123 
left puzzle to continue with stripe wallets creation
=> #123 wallets tab

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/main/resources/public/css/main.css, src/main/resources/public/js/getProject.js, src/main/resources/templates/project.html
PR for #135 
Moved project wallet endpoints to WalletsApi.
Added endpoint and front-end JQuery for creation and display of the real Stripe Wallet.
Puzzles to continue work.
=> #135 Create Stripe Wallet

src/test/java/com/selfxdsd/selfweb/api/output/JsonTaskTestCase.java
@Lumi3011 Started tests for JsonTask.
=> started unitests for JsonTask

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/resources/public/js/contractsService.js, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/templates/project.html
Fixes #142 
Left puzzle to implement the backend endpoint properly, once we have this
logic implemented in self-core.
=> #142 Update Contract form + backend scaffolding and puzzle

src/test/java/com/selfxdsd/selfweb/api/output/JsonTaskTestCase.java
Fixes #141 
I wrote test for the JsonTask class.
=> Finished tests for class JsonTask

src/main/resources/public/css/main.css, src/main/resources/templates/index.html
Created cards design for plans section. #146
=> Added Plans section to homepage

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/templates/header.html, src/main/resources/templates/index.html, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java
PR for #149 
Finished implementing "mark project contract for removal"
Left puzzle to continue with 'Restore Contract' functionality.
=> #149 Finished Mark Project Contract For Removal

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/templates/header.html, src/main/resources/templates/index.html, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java
PR for #151 
Finished 'Mark Contributor Contract For Removal'.
A Contributor can now mark one of their contracts for removal.
=> #151 Mark Contributor Contract For Removal

src/main/resources/public/js/confirmDialog.js, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/templates/project.html
=> #156 Confirm dialog before removing a contract.

src/main/resources/public/css/main.css, src/main/resources/public/js/getAndAddContracts.js
Fixes #158. Tooltip is not flickering now. I also move it on the left of the icon so the user can see better which icon the tooltip is assigned to.
=> Resolved tooltip flickering

src/test/java/com/selfxdsd/selfweb/api/output/JsonContractTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonProjectTestCase.java
Wrote the UnitTests for JsonContract #162
=> Tests for JsonContract output class

src/main/resources/public/js/getProject.js, src/main/resources/templates/project.html
=> #161 Added update cash limit form for real wallet.

src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/test/java/com/selfxdsd/selfweb/api/WalletsApiTestCase.java
=> #139 Add+tested update cash limit for WalletsApi.

src/test/java/com/selfxdsd/selfweb/api/output/JsonContractTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonWalletTestCase.java
Finished UnitTest for JsonWallet output class #166
=> Wrote Unit Tests for JsonWallet

src/main/java/com/selfxdsd/selfweb/api/BaseApiController.java, src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/main/resources/public/js/getProject.js, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/WalletsApiTestCase.java
=> #170 Frontend update cash limit integrated with backend.

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java
PR for #155 
- left puzzle to use the real contract restore api whan available.
=> #170 Restore contract with placeholder implemented + tested.

src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/test/java/com/selfxdsd/selfweb/api/WalletsApiTestCase.java
=> #137 Wallet activation endpoint implemented+tested.

src/test/java/com/selfxdsd/selfweb/api/output/JsonInvoicedTaskTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonWalletTestCase.java
Finished UnitTests for JsonInvoicedTask output class #173
=> Wrote tests for JsonInvoicedTask

src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/test/java/com/selfxdsd/selfweb/api/WalletsApiTestCase.java
=> #182 WalletsApi is now using user projects to find a project.

pom.xml, src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonPaymentMethod.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonPaymentMethods.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonWallet.java, src/main/resources/public/js/getProject.js, src/main/resources/templates/head.html, src/main/resources/templates/index.html, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/ProjectsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/WalletsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonProjectTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonWalletTestCase.java
Updated self-core to 0.0.36 and self-storage to 0.0.15;
Implemented "Add Payment Method" functionality for the real Stripe wallet (using Stripe SetupIntent mechanism);
Implemented JSON output classes for PaymentMethod and added them as attribute to each Wallet;
Display the payment methods in a table;
Added Bootstrap Toggle for the active/inactive toggle button of a PaymentMethod.
Also some changes on the Home Page, to make it look better.
=> Add Wallet payment method Implemented

src/main/java/com/selfxdsd/selfweb/PaymentMethodsApi.java, src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonPaymentMethod.java, src/main/resources/public/js/getProject.js, src/main/resources/public/js/paymentMethods.js, src/main/resources/templates/project.html
The user can now activate one of their payment methods.
Moved all PaymentMethod-related endpoints to class PaymentMethodsApi.
Implemented PaymentMethod activation endpoint.
Implemented the front-end. 
Only allow Wallet activation when there is an active PaymentMethod.
=> Implemented activation of PaymentMethod

src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoice.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/public/js/getProject.js, src/main/resources/public/js/wallets.js, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonContractTestCase.java
Fixes #189 
We are now working with EUR instead of USD.
Changed all front-end display of the currencies from USD to EUR.
=> #189 Front-End in EURO

src/main/resources/public/js/wallets.js, src/main/resources/templates/project.html
=> #192 Color for the Limit Cash in Real Wallet.

src/test/java/com/selfxdsd/selfweb/api/output/JsonContractTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonInvoicedTaskTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonPayoutMethodTestCase.java
Finished UnitTests for JSON output class JsonPayoutMethod #178
=> Wrote tests for JsonPayoutMethod

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ProjectManagersApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonProjectManager.java, src/main/resources/public/js/getPms.js, src/main/resources/templates/project.html, src/main/resources/templates/projectManagers.html, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/ProjectsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonProjectTestCase.java
Fixes #193 
Updated self-core to 0.0.38 and self-storage to 0.0.16;
Made required backend updates;
Made required front-end updates.
PM Commission is now a percentage from the Task's value.
=> #193 PM commission as Percentage

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/resources/public/js/getAndAddContracts.js
PR for #180 
- left puzzle to implement `restoreContract()` on frontend
=> #180 ContractsApi "mark for removal" endpoints updated.

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/PaymentMethodsApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/public/js/getProject.js, src/main/resources/public/js/invoiceToPdf.js, src/main/resources/public/js/wallets.js, src/main/resources/templates/contributor.html, src/main/resources/templates/project.html
Fixes #198 
We now display all Invoices of a Contract in a table side-by-side with the Tasks (analogue to Contributor Dashboard page);
Adapted ContractsApi endpoints (GET invoices, GET invoice, PUT payInvoice);
Changes in the front-end;
Pulled out invoiceToPdf JS function in its own file and reused it (it was duplicated before);
Other minor changes in text and styling of Project Overview tab;
Screenshot:
=> #198 Display all Invoices in Project Contracts Tab

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/resources/templates/project.html
PR for #144 
Finished the backend endpoint for updating a Contract (update hourly rate). 
Updated the hourly rate input fields to accept 2 decimals (before, they only accepted integers).
=> #144 finished update Contract functionality (update hourlyRate)

src/main/resources/public/js/getAndAddContracts.js
=> #203 Load Contracts Only on Tab Click.

src/main/resources/public/js/getOrgRepos.js, src/main/resources/templates/repositories.html
=> #209 Added Info Text about Github Orgs

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/PaymentMethodsApi.java, src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/java/com/selfxdsd/selfweb/api/input/ContractInput.java, src/main/java/com/selfxdsd/selfweb/api/input/PmInput.java, src/main/java/com/selfxdsd/selfweb/api/input/RepoInput.java, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java
Fixes #212 
Also removed redundant ``this.self`` from ContractsApi.
=> #212 Pattern Validation for all String Inputs

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/input/ContractInput.java, src/main/resources/templates/project.html
Fixes #216 
Min hourly rate is 8 EUR;
Max hourly rate is 300 EUR;
=> #216 hourlyRate min 8 max 300

src/main/resources/public/js/getAndAddContracts.js
- added a helper function to show loading animation to any data table.
(this should be called before ajax call)
- removed dead code of loading logic.
closes #215
=> #215 Show "Loading" Circle When Loading Contracts.

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java
PR for #179 
Finished restore contract front-end;
finished restore contract back-end;
removed puzzles.
=> #179 restore contract finished

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java
Fixes #228 
Updated to core 42 and storage 19;
Left puzzle to implement Remove Project.
=> #228 update core 42, storage 19 and puzzle

src/main/java/com/selfxdsd/selfweb/api/BaseApiController.java
=> #183 Constraint violation exception handler.

src/main/resources/public/css/main.css
=> #222 Gravatar user image has fixed size.

src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/main/java/com/selfxdsd/selfweb/api/output/AbstractJsonArray.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContracts.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContributor.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonWallet.java, src/main/resources/public/css/main.css, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/public/js/getProject.js, src/main/resources/public/js/wallets.js, src/main/resources/templates/contributor.html, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/WalletsApiTestCase.java
Fixes #223 
* On the Contributor Dashboard page we display the wallet type for each Contract
* Fixed bug regarding the wallet pie chart + cleaned JS code.
* Fixed other small display bugs. 
* Added "Are you sure..." question modal for the Pay Invoice icon.
=> #223 Better Wallet Info

src/test/java/com/selfxdsd/selfweb/api/output/JsonPayoutMethodTestCase.java
=> #196 Removed puzzle.

pom.xml
=> #269 core 43, storage 20

src/main/resources/public/js/getAndAddContracts.js
=> #245 "Github Username" field err is not displayed when search anymore.

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/wallets.js
Fixes #244
- also empty Invoices can't be paid or downloaded as pdf anymore.
=> #244 After paying Invoice, new active Invoice is shown.

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/input/ContractInput.java, src/main/resources/templates/project.html
=> #274 min hourly rate 15 EUR

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/wallets.js
Fixes #271 
We show the loading circle when paying the invoice.
Small bugfixes.
=> #271 show loading when paying invoice

src/main/resources/public/js/getProject.js
=> #249 "Update cash limit" pop-up closes when clicking outside of it.

src/main/resources/public/js/getProject.js
=> #265 "Update cash limit" closes itself when limit updated.

src/main/resources/public/css/main.css, src/main/resources/templates/header.html
Fixes #250 
Also removed the hamburger menu button from the mobile view. Instead of that, the user's avatar is shown directly and the drop-down menu appears when you click on it.
=> #250 fix show of unauthenticated elements

pom.xml, src/main/java/com/selfxdsd/selfweb/api/PayoutMethodsApi.java, src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/main/java/com/selfxdsd/selfweb/api/input/BillingInfoInput.java, src/main/java/com/selfxdsd/selfweb/api/input/validators/ValidCountryValidator.java, src/main/resources/public/js/payoutMethods.js, src/main/resources/public/js/wallets.js, src/main/resources/templates/contributor.html, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/input/validators/ValidCountryValidatorTestCase.java
Fixes #284 
* Contributor has to enter billing info when creating the Payout Method
* Project BillingInfo form updated.
* Better validation of the BillingInfo input form.
* Contributor billing info is sent to Stripe as data of the Account.
=> #284 BillingInfo formular for the Contributor

src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/projectSettings.js, src/main/resources/templates/project.html
Fixes #290 
Implemented Settings tab and the Delete Project button.
Delete Project button is active only if the Project has 0 Contracts (all contracts have been removed).
Backend endpoints for contractCound and deleteProject implemented.
Logging for ProjectsApi class.
Other small improvements.
=> #290 Settings Tab, Delete Project Implemented

src/main/java/com/selfxdsd/selfweb/UserController.java, src/main/resources/templates/header.html, src/main/resources/templates/user.html
=> #236 Implemented "User profile" page.

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/templates/project.html
=> #294 Better Table Loading Approach.

src/main/java/com/selfxdsd/selfweb/SelfWebApplication.java, src/main/java/com/selfxdsd/selfweb/api/PingApi.java, src/main/resources/application.properties, src/main/resources/templates/badge.html
fixes #298 
Added the ``/ping`` endpoint which also returns the version of the app.
=> #298 ping endpoint for self-web

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html
=> #297 Tables loading improvement on Contributor dashboard.

src/main/resources/public/js/getContributor.js
=> #302 Fixed Broken Contract Agenda Button on Contributor Dashboard.

src/main/resources/public/js/wallets.js
=> #282 Real wallet is now correctly shown after setup

src/main/resources/templates/project.html
=> #241. Fixed typo in "Update contract" card.

src/main/resources/templates/index.html
Fix for #237 
Maybe this PR include more changes than expected because fixing images resizing when zooming in/out ended up fixing some layout related code.
- Current behaviour (25% zoom)
- Fixed  (25% zoom)
- iPad
-iPhone
=> #237 fix images resizing when zooming

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html
Fixes #315 
Updated to self-core 52 and self-storage 24;
Backend endpoint for download of the PlatformInvoice for Contributor;
Front-end changes on the Contributor Dashboard page (download PlatformInvoice icon for Invoices paid with a real wallet).
=> #315 Download Platform Invoice for Contributor

src/main/resources/public/css/main.css
Added space between contracts tab tables on mobile #267
=> Space between tables

src/main/resources/public/js/getProject.js, src/main/resources/public/js/wallets.js
Fix for #248 
I'm not sure this is best way to fix that issue; 
WDYT @criske?
=> #248 wallet pie chart is now updating when new limit is set

pom.xml, src/main/java/com/selfxdsd/selfweb/InvoicesController.java, src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/java/com/selfxdsd/selfweb/api/InvoicesApi.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonPlatformInvoice.java, src/main/resources/templates/contributor.html, src/main/resources/templates/header.html, src/main/resources/templates/invoices.html
Fixes #331 
Added a page for admins where they can download platform invoices, as well as their corresponding project invoices.
=> #331 Invoices page for Admins

src/main/resources/public/css/main.css
Payment Methods Table is now scrollable on mobile so it can fit the screen #252
=> Table size on mobile

src/main/resources/templates/project.html
Auto scroll and auto focus is now working as expected on mobile devices when pressing certain buttons for contracts and payments #266
=> Auto-scroll and auto focus fixed on mobile

src/main/resources/public/js/getAndAddContracts.js
Fix for #246 
Now if the user try to add a contract with existing username and role this error will show:
=> #246 show a descriptive error message when adding same contract

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getOrgRepos.js, src/main/resources/templates/head.html, src/main/resources/templates/project.html, src/main/resources/templates/repositories.html
=> #343 Global provider variable.

src/main/java/com/selfxdsd/selfweb/UserController.java, src/main/java/com/selfxdsd/selfweb/api/Users.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getProject.js, src/main/resources/templates/head.html, src/main/resources/templates/user.html, src/test/java/com/selfxdsd/selfweb/UserControllerTestCase.java, src/test/java/com/selfxdsd/selfweb/api/UsersTestCase.java
=> #347 Global profile variable.

src/main/resources/public/js/getProject.js
=> #350 Fixed pm link on "managed by" project section.

src/main/java/com/selfxdsd/selfweb/LoginProducer.java, src/test/java/com/selfxdsd/selfweb/LoginProducerTestCase.java
=> LoginProducer unit tests for Github and Gitlab providers.

src/main/resources/public/css/main.css
The login buttons on mobile are now aligned on center #353
=> Styled login buttons on mobile

src/main/java/com/selfxdsd/selfweb/api/input/ContractInput.java, src/test/java/com/selfxdsd/selfweb/api/input/validators/ContractValidatorTestCase.java
=> #359 Allow usernames with dot in contract 

src/main/java/com/selfxdsd/selfweb/api/input/RepoInput.java, src/test/java/com/selfxdsd/selfweb/api/input/validators/RepoValidatorTestCase.java
Fix for #361
No payment for this one, it was almost copy-past :)
=> #361 allow dot (.) in repo's owner

src/main/resources/public/css/main.css, src/main/resources/templates/head.html
Modified the authenticated avatar so it's displayed in row now. #357
=> Authenticated-357

src/main/resources/templates/footer.html
Fixes #366 
Added the links to terms and co; data privacy and cookies policy in the footer.
=> #366 documents links in the footer

src/main/resources/templates/project.html
=> #363 Stripe add card consent text

src/main/resources/templates/project.html
=> #379 write badges URL on successful activation

src/main/java/com/selfxdsd/selfweb/api/input/validators/ValidCountryValidator.java, src/main/resources/templates/contributor.html, src/main/resources/templates/project.html
Fixes #372 
Added Malaysia and Mexico to the list of Stripe-supported countries.
=> #372 added Malaysia and Mexico

src/main/java/com/selfxdsd/selfweb/api/PayoutMethodsApi.java, src/test/java/com/selfxdsd/selfweb/api/PayoutMethodsApiTestCase.java
=> #385 PayoutMethodsApi.deleteStripeConnectAccount implemented and tested

src/main/java/com/selfxdsd/selfweb/api/PaymentMethodsApi.java, src/main/resources/public/js/paymentMethods.js, src/main/resources/public/js/wallets.js, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/PaymentMethodsApiTestCase.java
=> #371 Allow Deactivation Of All PaymentMethods.

pom.xml, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoice.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js
Fixes #390 
Status of latest payment of an Invoice is now displayed on the Invoice row as an exclamation mark, if the payment is failed. If the payment is successful, the status is as before ('Paid').
=> #390 Display Status Of Latest Payment

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/public/js/wallets.js
PR for #393 
Updated the payInvoice endpoint to return the Payment information;
Updated the invoice payment display logic to display failed payment info properly;
=> #393 Display Invoice Payment Updated

src/main/resources/templates/badge.html, src/main/resources/templates/contributor.html, src/main/resources/templates/cookies.html, src/main/resources/templates/footer.html, src/main/resources/templates/index.html, src/main/resources/templates/invoices.html, src/main/resources/templates/project.html, src/main/resources/templates/projectManagers.html, src/main/resources/templates/repositories.html, src/main/resources/templates/user.html
=> #395 cookies stuff template and put after body

src/main/resources/public/js/confirmDialog.js, src/main/resources/public/js/payoutMethods.js, src/main/resources/templates/contributor.html
Fixes #402 
The two buttons are now aligned;
The buttons are deactivated and the spinner is displayed when an action takes place;
Modal question on Delete press;
=> #402 PayoutMethods align Delete and Dashboard Buttons

pom.xml, src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/main/resources/public/js/confirmDialog.js, src/main/resources/public/js/wallets.js, src/test/java/com/selfxdsd/selfweb/api/WalletsApiTestCase.java
=> #389 Delete Fake Wallet On Real Wallet Activation.

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/public/js/payoutMethods.js, src/main/resources/public/js/wallets.js
=> #403 revised questions

src/main/java/com/selfxdsd/selfweb/api/PaymentMethodsApi.java, src/test/java/com/selfxdsd/selfweb/api/PaymentMethodsApiTestCase.java
=> #405 Activate by default 1st added PaymentMethod.

src/main/java/com/selfxdsd/selfweb/api/PaymentMethodsApi.java, src/main/resources/public/js/paymentMethods.js, src/main/resources/public/js/wallets.js, src/test/java/com/selfxdsd/selfweb/api/PaymentMethodsApiTestCase.java
=> #407 Allow Removal Of A Payment Method.

src/main/resources/public/js/wallets.js
=> #411 Remove fake when real wallet is detected on listing.

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/java/com/selfxdsd/selfweb/api/InvoicesApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/public/js/wallets.js, src/main/resources/templates/invoices.html, src/test/java/com/selfxdsd/selfweb/api/InvoicesApiTestCase.java
=> #417 Showing pdf invoice in a new tab.

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/templates/project.html
Added tab for tasks table and also an empty table #416
=> Add tab and tasks table

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ProjectManagersApi.java, src/main/java/com/selfxdsd/selfweb/api/input/PmInput.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoicedTask.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonProjectManager.java, src/main/resources/public/js/getPms.js, src/main/resources/templates/contributor.html, src/main/resources/templates/projectManagers.html, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/ProjectManagersApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/ProjectsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonInvoicedTaskTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonProjectTestCase.java
PR for #422 
Updated deps to self-core 72 and self-storage 68 and made the required changes;
Added the Contributor Commission to the ProjectManagers page;
=> #422 Contributor Commission Added To ProjectManagers Page

src/main/resources/public/js/getProject.js, src/main/resources/templates/project.html
=> #420 Info Badge After Activating A Repo.

src/main/resources/templates/invoices.html
=> #426 account for Reverse VAT

src/main/resources/templates/contributor.html
=> #424 link to contributor commmission/invoicing page

pom.xml
=> #429 core 74, storage 69

src/main/resources/public/js/wallets.js
=> #428 Better Alert For 500 Payment.

src/main/resources/templates/index.html
=> #438 chatbot

src/main/resources/templates/footer.html
=> #434 Added self-xdsd social media links to footer.

src/main/resources/templates/footer.html
=> #448 badge in footer

pom.xml
=> closes #453 core 92, storage 73

src/main/resources/public/js/getAndAddContracts.js
=> #463 totalAmount parsing fixed
