self-xdsd/self-web

pom.xml, src/main/java/com/selfxdsd/selfweb/api/ProjectManagersApi.java, src/main/java/com/selfxdsd/selfweb/api/Projects.java, src/main/java/com/selfxdsd/selfweb/api/Repositories.java, src/main/resources/application.properties
Should fix #50 
We now let Spring Boot use Jackson when marshalling/unmarshalling input/output objects. 
However, we still use JSON-P internally, to handle build JsonObjects and JsonArrays.
=> #50 using Jackson instead of JSON-B

src/main/resources/public/js/getOrgRepos.js
Fixes #127. Added links to the repos on the Organizations Tab.
=> Org Repos Tab #127

src/main/java/com/selfxdsd/selfweb/api/ContributorApi.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html
A Contributor should be able to remove (mark for removal) one of their contracts, from the 'Contributor Dashboard' page.
Front end and backend scaffolding implemented.
=> Mark contributor contract for removal

src/main/resources/public/js/confirmDialog.js, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html
Closes #160 
- also fixed bug where confirm dialog button click listener was leaking.
=> #160 Confirm on removing a contract from contributor dashboard.

src/main/resources/templates/project.html
Fixes #210 
Added a red message on the "Add Payment Method" form, informing the user to not add a real card, when we are in Test.
=> #210 card warning when in Test

pom.xml, src/main/java/com/selfxdsd/selfweb/api/input/ContractInput.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonInvoice.java, src/main/java/com/selfxdsd/selfweb/api/output/JsonTask.java, src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js, src/main/resources/templates/contributor.html, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/ContributorApiTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonContractTestCase.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonTaskTestCase.java
On the Contributor Dashboard we now display only the ammounts which they are going to receive (without PM commission, since it's not their business).
Added JsonInvoice.amount and JsonContract.revenue.
Added value column for Tasks tables. 
Updated self-core to 0.0.41 and self-storage to 0.0.18.
Some other small changes.
=> Better Revenue Display on Contributor Dashboard

src/main/java/com/selfxdsd/selfweb/api/BaseApiController.java, src/main/resources/public/js/wallets.js
If we cannot make the payment for any reason (invoice already paid, contributor's account not set up etc), we show an alert message informing the user about it.
=> #224 Show Alert On Payment Problem

pom.xml, src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java, src/main/java/com/selfxdsd/selfweb/api/input/StripeWalletInput.java, src/main/java/com/selfxdsd/selfweb/api/input/validators/NoSpecialChars.java, src/main/java/com/selfxdsd/selfweb/api/input/validators/NoSpecialCharsValidator.java, src/main/java/com/selfxdsd/selfweb/api/input/validators/ValidCountry.java, src/main/java/com/selfxdsd/selfweb/api/input/validators/ValidCountryValidator.java, src/main/resources/public/js/wallets.js, src/main/resources/templates/head.html, src/main/resources/templates/project.html, src/test/java/com/selfxdsd/selfweb/api/input/validators/NoSpecialCharsValidatorTestCase.java, src/test/java/com/selfxdsd/selfweb/api/input/validators/ValidCountryValidatorTestCase.java
Fixes #280 
Added the front-end form and validation;
Added backend param bean and validation;
Saving BillingInfo to Stripe Customer (wallet).
=> #280 Stripe BillingInfo front-end form and validation (fe + be)

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/wallets.js, src/main/resources/templates/contributor.html
- also added one puzzle for wallet activation and one for contracts table optimization.
fixes #253
=> #253 Contributor stripe dashboard opens in a new tab.

src/main/resources/public/js/contractsService.js, src/main/resources/public/js/getAndAddContracts.js
Fixes #242
- cleanup contractsService.js - at the moment we're doing all paging and filtering locally with `dataTables`, so there's no need to simulate server side paging in that service.
- getAndAddContract.js - cleaner way to show loading image in Contracts table: removed `dataTableShowLoading` function in favor of using `language.loadingRecords` setup property of `dataTable`).
=> #242 Fixed Contracts Table entries wrong display info.

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/getContributor.js
=> #306 Fixed Options Buttons Don't Work On 2+ Pages Of Table.

src/main/java/com/selfxdsd/selfweb/api/output/JsonProject.java, src/test/java/com/selfxdsd/selfweb/api/output/JsonProjectTestCase.java
Fixes #305 
We don't show the wallet's payment methods in JsonProject, because this slows the response time a lot when there are multiple Stripe PaymentMethods registered.
=> #305 don't show PaymentMethods in JsonProject

src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java, src/test/java/com/selfxdsd/selfweb/api/ContractsApiTestCase.java
Fixes #308 
Input contract hourly rate (for create or update) is rounded (half up) to 2 decimals before being multiplied by 100. Thus, the resulting BigDecimal will always be an integer representing the cents.
User input: 16.44 => 1644 cents; 16.4435 => 1644 cents; 16.4451 => 1645 cents.
=> #308 Contract hourly rate rounded up

src/main/resources/public/js/getAndAddContracts.js, src/main/resources/public/js/wallets.js
fixes #300
Also active invoices with 0 total amount can't be downloaded. (I think this bug was reintroduced after we moved the pdf generation logic on server)
=> #300 Allow Invoice Payment Only If totalAmount >= 108 EUR

src/main/resources/public/js/getAndAddContracts.js
Fixes #285
Adding a new contributor, removing restoring contracts.
Updating a contract
Display contract invoices and tasks
---
In order the achieve this, I had to do some code refactoring: the  "rendering" for options column is done in one place in a calllback provided when setting up the table with Datatables API.
Now any table updates like adding/updating/marking contracts are done by using Datatables API with plain js objects as data model.
=> #285 Updates on Project Contracts will not reload the whole table.

src/main/resources/public/js/getContributor.js
Fixes #327 
Contract object passed to task table row wasn't have the `id.provider` property set.
=> #327 Fixed Contributor Dashboard Tasks table issue links.

src/main/java/com/selfxdsd/selfweb/api/Repositories.java, src/main/resources/public/js/getManagedRepos.js, src/main/resources/templates/repositories.html, src/test/java/com/selfxdsd/selfweb/api/RepositoriesTestCase.java
Fixes #340 
Implemented and tested Repositories.managedRepos() backend;
Implemented `Managed Repos` tab on the Repositories page.
=> #340 Managed Repos Tab Implemented

src/main/resources/templates/footer.html, src/main/resources/templates/head.html
Fixes #356
Added Cookies Settings. The user can opt in/out of Analytics, Social and Marketing cookies.
The banned appears on the bottom left side of the page and uses the same colors as the overall webside.
=> #356 Cookies Banner/Settings Added

src/main/resources/templates/contributor.html, src/main/resources/templates/project.html
Fixes #364 
Renamed the field's label and error message from "Tax ID" to "VAT Number".
=> #364 Tax ID label -> VAT Number

src/main/resources/public/css/main.css, src/main/resources/public/js/payoutMethods.js, src/main/resources/templates/contributor.html
Delete button for the payout methods #387
=> Started the delete of payout methods

src/main/resources/public/js/wallets.js
pr for #413
Also:
- disabled toggle input while method it's being removed. (before only the remove button was disabled)
- after removal, if there are no payment methods anymore, `#noRealPaymentMethods` panel
is shown instead of "warning message".
=> #413 Fixed "arePaymentMethodsDeactivated" function.

pom.xml, src/main/java/com/selfxdsd/selfweb/api/Repositories.java, src/main/resources/templates/repositories.html, src/test/java/com/selfxdsd/selfweb/api/RepositoriesTestCase.java
Fixes #443 
Updated to core 88 and storage 71.
The user's personal repos will now be read server-side to ensure that the private repos are included as well. 
Added unit tests.
Left puzzle for front-end.
=> #443 Backend for Personal Repos
